# Single TLU network
*Hebb's Rule: Cells that fire together wire together*

*TLU - Linear threshold Unit*

In [2]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

In [9]:
iris = load_iris()
X = iris['data']
y = iris['target']
model = Perceptron()
model.fit(X, y)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [14]:
model.predict(iris.data)
#(iris['target']==0).astype(np.int)

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1])

# Image classifier using fashion MNIST

In [15]:
import tensorflow as tf
from tensorflow import keras

In [18]:
tf.__version__

'1.14.0'

In [19]:
fashion_mnist = keras.datasets.fashion_mnist

In [21]:
(X_train_full, y_train_full), (X_test, y_test)= fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [30]:
# Scale dataset and create a validation dataset

X_valid, X_train = X_train_full[:5000]/255.0, X_train_full[5000:]/255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

In [29]:
# Adding class names to identify the target 'y' variable
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
               "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

In [38]:
# Create model using sequential API
model = keras.models.Sequential()
model.add(keras.layers.InputLayer(input_shape=[28,28]))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(300, activation='relu'))
model.add(keras.layers.Dense(100, activation='relu'))
model.add(keras.layers.Dense(10, activation='softmax'))

In [39]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 300)               235500    
_________________________________________________________________
dense_7 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_8 (Dense)              (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [41]:
model.layers

In [46]:
model.get_weights()

[array([[ 0.02550611, -0.02086007, -0.05837977, ..., -0.00574809,
         -0.00418356,  0.03361554],
        [ 0.05586438,  0.02066121, -0.06989749, ...,  0.0365214 ,
          0.00113191,  0.0644293 ],
        [-0.02672585,  0.02523105,  0.00174233, ...,  0.01229561,
          0.02180742,  0.00823364],
        ...,
        [ 0.03111353,  0.06490807, -0.01821039, ..., -0.0658093 ,
         -0.02130804,  0.0014559 ],
        [ 0.02620674,  0.07198261,  0.04219073, ..., -0.0661746 ,
         -0.04744989,  0.01624369],
        [-0.05424973, -0.00645354,  0.04177215, ..., -0.01345095,
          0.06528772, -0.03700545]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [47]:
model.compile(loss='sparse_categorical_crossentropy',
             optimizer='sgd',
             metrics=['accuracy'])

In [48]:
model.fit(X_train, y_train, epochs=30, validation_data=(X_valid, y_valid))

Train on 55000 samples, validate on 5000 samples
Epoch 1/30
55000/55000 [==============================] - 10s 185us/sample - loss: 0.7101 - acc: 0.7662 - val_loss: 0.5195 - val_acc: 0.8204
Epoch 2/30
55000/55000 [==============================] - 10s 184us/sample - loss: 0.4813 - acc: 0.8338 - val_loss: 0.4583 - val_acc: 0.8434
Epoch 3/30
55000/55000 [==============================] - 10s 178us/sample - loss: 0.4390 - acc: 0.8452 - val_loss: 0.4032 - val_acc: 0.8668
Epoch 4/30
55000/55000 [==============================] - 10s 190us/sample - loss: 0.4123 - acc: 0.8549 - val_loss: 0.4046 - val_acc: 0.8610
Epoch 5/30
55000/55000 [==============================] - 11s 205us/sample - loss: 0.3943 - acc: 0.8610 - val_loss: 0.3879 - val_acc: 0.8654
Epoch 6/30
55000/55000 [==============================] - 11s 208us/sample - loss: 0.3780 - acc: 0.8661 - val_loss: 0.3849 - val_acc: 0.8640
Epoch 7/30
55000/55000 [==============================] - 11s 202us/sample - loss: 0.3660 - acc: 0.8709 -

In [49]:
# Evalauate the model on test set
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 1s 109us/sample - loss: 66.0953 - acc: 0.8442


[66.09526018251155, 0.8442]

In [58]:
# Make predictions
# model.predict_proba(X_test[:30])
model.predict_classes(X_test[:30])
# Check predictions
#y_test[:3]

array([9, 2, 1, 1, 0, 1, 4, 4, 5, 7, 4, 5, 5, 3, 4, 1, 2, 2, 8, 0, 2, 5,
       7, 5, 1, 4, 4, 0, 9, 3])

In [51]:
y_test[:3]

array([9, 2, 1], dtype=uint8)

# Regression MLP using sequential API

In [59]:
# Load California housing dataset
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [60]:
housing = fetch_california_housing()

In [63]:
# Get Train, test & validation data 
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full)

# Standardize the data for training
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

In [69]:
# Instantiate the model
model = keras.models.Sequential([keras.layers.Dense(30, activation='relu', input_shape=X_train.shape[1:]),
                                keras.layers.Dense(1)])
# Compile the model
model.compile(loss="mean_squared_error", optimizer="sgd")
history = model.fit(X_train, y_train, epochs=20,
                    validation_data=(X_valid, y_valid))
mse_test = model.evaluate(X_test, y_test)
X_new = X_test[:3] # pretend these are new instances
y_pred = model.predict(X_new)

Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 2s 149us/sample - loss: 0.7380 - val_loss: 0.4417
Epoch 2/20
11610/11610 [==============================] - 1s 80us/sample - loss: 0.4361 - val_loss: 0.4073
Epoch 3/20
11610/11610 [==============================] - 1s 88us/sample - loss: 0.4078 - val_loss: 1.2185
Epoch 4/20
11610/11610 [==============================] - 1s 97us/sample - loss: 0.4003 - val_loss: 1.4687
Epoch 5/20
11610/11610 [==============================] - 1s 95us/sample - loss: 0.3943 - val_loss: 0.8485
Epoch 6/20
11610/11610 [==============================] - 1s 92us/sample - loss: 0.4758 - val_loss: 0.6704
Epoch 7/20
11610/11610 [==============================] - 1s 82us/sample - loss: 0.3894 - val_loss: 0.3782
Epoch 8/20
11610/11610 [==============================] - 1s 67us/sample - loss: 0.3810 - val_loss: 0.4037
Epoch 9/20
11610/11610 [==============================] - 1s 74us/sample - loss: 0.3770 - val_

# Wide and Deep neural network using Functional API
Paper link [here](https://arxiv.org/pdf/1606.07792.pdf)

In [71]:
# Full inputs passed both as wide and deep inputs
input_ = keras.layers.Input(shape=X_train.shape[1:])
hidden1 = keras.layers.Dense(30, activation="relu")(input_)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
concat = keras.layers.Concatenate()([input_, hidden2])
output = keras.layers.Dense(1)(concat)
model = keras.Model(inputs=[input_], outputs=[output])

In [72]:
# Compile the model
model.compile(loss="mean_squared_error", optimizer="sgd")
history = model.fit(X_train, y_train, epochs=20,
                    validation_data=(X_valid, y_valid))
mse_test = model.evaluate(X_test, y_test)
X_new = X_test[:3] # pretend these are new instances
y_pred = model.predict(X_new)

Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 2s 197us/sample - loss: 0.7236 - val_loss: 21.2803
Epoch 2/20
11610/11610 [==============================] - 1s 112us/sample - loss: 0.4873 - val_loss: 0.4761
Epoch 3/20
11610/11610 [==============================] - 1s 122us/sample - loss: 0.4247 - val_loss: 6.1241
Epoch 4/20
11610/11610 [==============================] - 1s 103us/sample - loss: 0.3945 - val_loss: 1.5358
Epoch 5/20
11610/11610 [==============================] - 1s 114us/sample - loss: 0.3845 - val_loss: 1.3352
Epoch 6/20
11610/11610 [==============================] - 2s 148us/sample - loss: 0.3752 - val_loss: 1.1851
Epoch 7/20
11610/11610 [==============================] - 1s 127us/sample - loss: 0.3695 - val_loss: 0.5659
Epoch 8/20
11610/11610 [==============================] - 1s 124us/sample - loss: 0.3620 - val_loss: 0.7717
Epoch 9/20
11610/11610 [==============================] - 1s 111us/sample - loss: 0.38

## Splitting the available features and passing them differently

In [73]:
input_A = keras.layers.Input(shape=[5], name="wide_input")
input_B = keras.layers.Input(shape=[6], name="deep_input")
hidden1 = keras.layers.Dense(30, activation="relu")(input_B)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
concat = keras.layers.concatenate([input_A, hidden2])
output = keras.layers.Dense(1, name="output")(concat)
model = keras.Model(inputs=[input_A, input_B], outputs=[output])

In [75]:
model.compile(loss="mse", optimizer=keras.optimizers.SGD(lr=1e-3))

X_train_A, X_train_B = X_train[:, :5], X_train[:, 2:]
X_valid_A, X_valid_B = X_valid[:, :5], X_valid[:, 2:]
X_test_A, X_test_B = X_test[:, :5], X_test[:, 2:]
X_new_A, X_new_B = X_test_A[:3], X_test_B[:3]

history = model.fit((X_train_A, X_train_B), y_train, epochs=20,
                    validation_data=((X_valid_A, X_valid_B), y_valid))
mse_test = model.evaluate((X_test_A, X_test_B), y_test)
y_pred = model.predict((X_new_A, X_new_B))

Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 2s 165us/sample - loss: 2.1278 - val_loss: 2.0854
Epoch 2/20
11610/11610 [==============================] - 1s 91us/sample - loss: 0.7899 - val_loss: 1.8267
Epoch 3/20
11610/11610 [==============================] - 1s 111us/sample - loss: 0.6560 - val_loss: 1.6852
Epoch 4/20
11610/11610 [==============================] - 1s 95us/sample - loss: 0.5955 - val_loss: 1.5793
Epoch 5/20
11610/11610 [==============================] - 1s 89us/sample - loss: 0.5576 - val_loss: 1.5067
Epoch 6/20
11610/11610 [==============================] - 1s 82us/sample - loss: 0.5303 - val_loss: 1.4352
Epoch 7/20
11610/11610 [==============================] - 1s 96us/sample - loss: 0.5093 - val_loss: 1.4013
Epoch 8/20
11610/11610 [==============================] - 1s 95us/sample - loss: 0.4925 - val_loss: 1.4129
Epoch 9/20
11610/11610 [==============================] - 1s 108us/sample - loss: 0.4790 - va

## Having an auxiliary output

In [76]:
input_A = keras.layers.Input(shape=[5], name="wide_input")
input_B = keras.layers.Input(shape=[6], name="deep_input")
hidden1 = keras.layers.Dense(30, activation="relu")(input_B)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
concat = keras.layers.concatenate([input_A, hidden2])
output = keras.layers.Dense(1, name="main_output")(concat)
aux_output = keras.layers.Dense(1, name="aux_output")(hidden2)
model = keras.Model(inputs=[input_A, input_B], outputs=[output, aux_output])

In [79]:
model.compile(loss=["mse", "mse"], loss_weights=[0.9, 0.1], optimizer="sgd")

In [83]:
history = model.fit(
    [X_train_A, X_train_B], [y_train, y_train], epochs=20,
    validation_data=([X_valid_A, X_valid_B], [y_valid, y_valid]))

Train on 11610 samples, validate on 3870 samples
Epoch 1/20
11610/11610 [==============================] - 2s 210us/sample - loss: 0.8986 - main_output_loss: 0.7850 - aux_output_loss: 1.9194 - val_loss: 3.7208 - val_main_output_loss: 3.9812 - val_aux_output_loss: 1.3603
Epoch 2/20
11610/11610 [==============================] - 1s 107us/sample - loss: 1.9947 - main_output_loss: 2.0351 - aux_output_loss: 1.6278 - val_loss: 2.0101 - val_main_output_loss: 1.9513 - val_aux_output_loss: 2.5320
Epoch 3/20
11610/11610 [==============================] - 1s 112us/sample - loss: 0.5899 - main_output_loss: 0.5058 - aux_output_loss: 1.3466 - val_loss: 0.7157 - val_main_output_loss: 0.6552 - val_aux_output_loss: 1.2599
Epoch 4/20
11610/11610 [==============================] - 2s 136us/sample - loss: 0.4987 - main_output_loss: 0.4376 - aux_output_loss: 1.0486 - val_loss: 0.7690 - val_main_output_loss: 0.7399 - val_aux_output_loss: 1.0309
Epoch 5/20
11610/11610 [==============================] - 1s 10

In [84]:
# return losses
total_loss, main_loss, aux_loss = model.evaluate(
    [X_test_A, X_test_B], [y_test, y_test])

5160/5160 [==============================] - 0s 57us/sample - loss: 0.3777 - main_output_loss: 0.3594 - aux_output_loss: 0.5297


In [85]:
# Get predictions for both the outputs
y_pred_main, y_pred_aux = model.predict([X_new_A, X_new_B])

In [86]:
y_pred_main

array([[2.5713506],
       [3.119655 ],
       [2.9617078]], dtype=float32)

In [87]:
y_pred_aux

array([[2.7912395],
       [2.9572034],
       [3.2304718]], dtype=float32)

In [88]:
y_test

array([0.734, 2.57 , 2.754, ..., 2.196, 2.267, 1.402])